// Monkey patch jQuery 1.3.1+ css() method to support CSS 'transform'
// property uniformly across Safari/Chrome/Webkit, Firefox 3.5+, IE 9+, and Opera 11+.
// 2009-2011 Zachary Johnson www.zachstronaut.com
// Updated 2011.05.04 (May the fourth be with you!)
// https://github.com/zachstronaut/jquery-css-transform/blob/master/jquery-css-transform.js

// Monkey patch jQuery 1.3.1+ to add support for setting or animating CSS
// scale and rotation independently.
// 2009-2010 Zachary Johnson www.zachstronaut.com
// Updated 2010.11.06
// https://github.com/zachstronaut/jquery-animate-css-rotate-scale/blob/master/jquery-animate-css-rotate-scale.js

(function($){function getTransformProperty(element){var properties=['transform','WebkitTransform','msTransform','MozTransform','OTransform'];var p;while(p=properties.shift()){if(typeof element.style[p]!='undefined'){return p;}}return'transform';}var _propsObj=null;var proxied=$.fn.css;$.fn.css=function(arg,val){if(_propsObj===null){if(typeof $.cssProps!='undefined'){_propsObj=$.cssProps;}else if(typeof $.props!='undefined'){_propsObj=$.props;}else{_propsObj={}}}if(typeof _propsObj['transform']=='undefined'&&(arg=='transform'||(typeof arg=='object'&&typeof arg['transform']!='undefined'))){_propsObj['transform']=getTransformProperty(this.get(0));}if(_propsObj['transform']!='transform'){if(arg=='transform'){arg=_propsObj['transform'];if(typeof val=='undefined'&&jQuery.style){return jQuery.style(this.get(0),arg);}}else if(typeof arg=='object'&&typeof arg['transform']!='undefined'){arg[_propsObj['transform']]=arg['transform'];delete arg['transform'];}}return proxied.apply(this,arguments);};})(jQuery);(function($){var rotateUnits='deg';$.fn.rotate=function(val){var style=$(this).css('transform')||'none';if(typeof val=='undefined'){if(style){var m=style.match(/rotate\(([^)]+)\)/);if(m&&m[1]){return m[1];}}return 0;}var m=val.toString().match(/^(-?\d+(\.\d+)?)(.+)?$/);if(m){if(m[3]){rotateUnits=m[3];}$(this).css('transform',style.replace(/none|rotate\([^)]*\)/,'')+'rotate('+m[1]+rotateUnits+')');}return this;};$.fn.scale=function(val,duration,options){var style=$(this).css('transform');if(typeof val=='undefined'){if(style){var m=style.match(/scale\(([^)]+)\)/);if(m&&m[1]){return m[1];}}return 1;}$(this).css('transform',style.replace(/none|scale\([^)]*\)/,'')+'scale('+val+')');return this;};var curProxied=$.fx.prototype.cur;$.fx.prototype.cur=function(){if(this.prop=='rotate'){return parseFloat($(this.elem).rotate());}else if(this.prop=='scale'){return parseFloat($(this.elem).scale());}return curProxied.apply(this,arguments);};$.fx.step.rotate=function(fx){$(fx.elem).rotate(fx.now+rotateUnits);};$.fx.step.scale=function(fx){$(fx.elem).scale(fx.now);};var animateProxied=$.fn.animate;$.fn.animate=function(prop){if(typeof prop['rotate']!='undefined'){var m=prop['rotate'].toString().match(/^(([+-]=)?(-?\d+(\.\d+)?))(.+)?$/);if(m&&m[5]){rotateUnits=m[5];}prop['rotate']=m[1];}return animateProxied.apply(this,arguments);}})(jQuery);